---
title: "Tech Review Review"
output: html_notebook
---

1: Business Understanding:

1.1: Business Objectives
  -Provide summary statistics for tech reviewers.
  -Provide leveled list of which tech reviewers reviews the highest quantity, and how harshly.
  

1.2: Assess Situation
  -.csv file with multiple tabs supplied.
  -No computational resources provided.
  -No paid time for project provided. 
  -Minimal requirements/deliverables provided for the project.
  -Possibly results in metric rankings that would bias evaluation of analysts or tech reviewers. Primary risk.


1.3: Data Mining Goals
  Success here will look like an even evaluation of each tech reviewer with appropriate weighting
  applied to distinguish method evaluations, validations, and routine testing to properly review tech
  reviewer productivity. Weighting will also be applied to the "C1 - C7" encoded variables which encode
  for quality errors. 
  

2: Data Understanding: 

  2.1: Describe Data

#tr.chris is completely empty
#tr.jeff having trouble importing
```{r}
#Import Data
library(tidyverse)
library(moderndive)
library(readxl)

filepath <- "C:/Users/mastl/Desktop/Grad_School/2021_tr.xlsx"

tr.df <- excel_sheets("C:/Users/mastl/Desktop/Grad_School/2021_tr.xlsx")


#tr.jeff <- read_xlsx(filepath, sheet = "Jeff B", skip = 8)
tr.hans <- read_xlsx(filepath, sheet = "Hans H", skip = 8)
tr.vir <- read_xlsx(filepath, sheet = "Vir P", skip = 8)
tr.kim <- read_xlsx(filepath, sheet = "Kim J", skip = 8)
tr.dolly <- read_xlsx(filepath, sheet = "Dolly W", skip = 8)
tr.clester <- read_xlsx(filepath, sheet = "Clester O", skip = 8)
tr.michael <- read_xlsx(filepath, sheet = "Michael K", skip = 8)
tr.chris <- read_xlsx(filepath, sheet = "Chris S", skip = 8)
tr.sarah <- read_xlsx(filepath, sheet = "Sarah C", skip = 8)
tr.dennis <- read_xlsx(filepath, sheet = "Dennis W", skip = 8)
tr.kelly <- read_xlsx(filepath, sheet = "Kelly L", skip = 8)

tr.reviewers <- list("hans" = tr.hans, 
                     "vir" =tr.vir, 
                     "kim" = tr.kim, 
                     "dolly" = tr.dolly, 
                     "clester" = tr.clester,
                     "michael" = tr.michael, 
                     "chris" = tr.chris, 
                     "sarah" = tr.sarah, 
                     "dennis" = tr.dennis, 
                     "kelly" = tr.kelly)

for(i in 1:10) {
  names(tr.reviewers[i])
  summary(tr.reviewers[[i]])
  dim(tr.reviewers[[i]])
}

```

